[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.21"
solc = "0.8.21"

ignored_warnings_from = ["test/TestHelpers.t.sol"]

remappings = [
  '@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/',
  '@openzeppelin/=lib/openzeppelin-contracts/',
  '@forge/=lib/forge-std/src/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
