[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"

optimizer_runs = 200

ignored_warnings_from = ["test/TestImports.t.sol"]

remappings = [
  # '@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/',
  '@solady/=lib/solady/src/',
  '@openzeppelin/=lib/openzeppelin-contracts/',
  '@forge/=lib/forge-std/src/',
]

# Much slower compile times when true, but helps with code size when true
via_ir = false

[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
shrink_sequence = true
preserve_state = false

[fmt]
single_line_statement_blocks = "single"
sort_imports = true
multiline_func_header = "params_first"
number_underscore = "thousands"
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
