#!/bin/bash

install_foundry() {
  if ! command -v foundryup &> /dev/null; then
    echo "Installing foundry..."
    curl -L https://foundry.paradigm.xyz | bash
  fi

  if ! command -v forge &> /dev/null; then
    foundryup || ~/.foundary/bin/foundryup
  fi
}

install_foundry

echo
echo "Installed"
forge --version
cast --version
anvil --version